### ISSUE TITLE
The `ResultFormat` enum used by `Restable` only includes the `json` case

### ISSUE THREAD

**Issue by adealmeida** [ryanbaldwin/Restivus#12]
When using a `Restable` we should be able to configure the response body using the `resultFormat: ResultFormat` variable. Currently we can only enable response bodies that are json decoded. We need to add support for other types. 

This is because the `ResultFormat` enum only has the one `.json` case

**Comment by ryanbaldwin** [comment]
ha! looks as though I half-baked my improvement. From our IRL conversation, the bug isn't so much having to do with your choice of accepted response type header, but rather that when defining a `ResopnseType = Raw` the accepted response type of `application/json` is still being sent up.

When `Raw`, now accepted response header should be sent.

**Comment by adealmeida** [comment]
I think also, you changed the default to be `application/json` right? And there was no way to configure it to be `raw` since there was no case for `.raw` in the `ResultFormat` enum.

**Comment by ryanbaldwin** [comment]
Yea, I removed the `.raw` ResultFormat because it’s redundant. There’s no need for it if the `ResponseType` is `Raw`.  The real bug is that the header still gets applied. 

A work around for you, for now, is to conform the request in question to `Interceptable` and, in the `intercept` method, remove the `Accept` header.

**Comment by ryanbaldwin** [comment]
This is fixed in v0.4.4. Release notes are here:

https://github.com/ryanbaldwin/Restivus/releases/tag/v0.4.4
